# Generated by Django 4.1.7 on 2023-02-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BASIC_LIBRARY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Library Name')),
                ('resume', models.TextField(verbose_name='Resume')),
                ('code', models.FileField(upload_to='', verbose_name='Zip File')),
                ('repository', models.URLField(verbose_name='Repository URL')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='BASIC_STRUCTURE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('install', models.TextField(verbose_name='Instalation')),
                ('usage', models.TextField(verbose_name='Usage')),
                ('review', models.TextField(verbose_name='Review')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='C_CATEGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catego_name', models.CharField(max_length=500, verbose_name='Category Name')),
                ('catego_resume', models.TextField(verbose_name='Resume')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='C_SUBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatego_name', models.CharField(max_length=200, verbose_name='Subcategory Name')),
                ('subcatego_resume', models.TextField(verbose_name='Resume')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='C_TYPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_typo', models.CharField(max_length=500, verbose_name='Genéric Name')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.c_catego')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.c_subc')),
            ],
        ),
        migrations.CreateModel(
            name='COMPONENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('c_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.c_type')),
            ],
        ),
        migrations.CreateModel(
            name='FULL_CODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='zips', verbose_name='full_code_zip')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='RB_CATEGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catego_name', models.CharField(max_length=500, verbose_name='Category Name')),
                ('catego_resume', models.TextField(verbose_name='Resume')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='RB_SUBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatego_name', models.CharField(max_length=500, verbose_name='Subcategory Name')),
                ('subcatego_resume', models.TextField(verbose_name='Resume')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
        ),
        migrations.CreateModel(
            name='RB_TYPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_typo', models.CharField(max_length=500, verbose_name='Genéric Name')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.rb_catego')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.rb_subc')),
            ],
        ),
        migrations.CreateModel(
            name='ROBOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Robot Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('resume', models.TextField(verbose_name='Resume')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('bot_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.full_code')),
                ('bot_comp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.component')),
                ('bot_struct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.basic_structure')),
                ('bot_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.rb_type')),
            ],
        ),
        migrations.CreateModel(
            name='CODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=44, verbose_name='Code')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.robot')),
            ],
        ),
        migrations.CreateModel(
            name='BASIC_COMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_for', models.TextField()),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.component')),
            ],
        ),
    ]
